In [17]:
import numpy as np
a=np.array([[1,3,2],[2,4,5]])
print(a)
print(a.shape)
b=np.arange(10,24,5)
print(b)
print(b.shape)
print(a.dot(b))
print(np.multiply(a,b))

[[1 3 2]
 [2 4 5]]
(2, 3)
[10 15 20]
(3,)
[ 95 180]
[[ 10  45  40]
 [ 20  60 100]]


In [19]:
import numpy as np
a=np.array([1,4,5,7])
print(a.reshape(1,4))
print(a)

[[1 4 5 7]]
[1 4 5 7]


In [21]:
import numpy as np
a=np.array([1.23456,2.34])
print(a.dtype)
a=np.array([1.6,2.34])
print(a.dtype)

float64
float64


In [26]:
import numpy as np
a=np.array([1,4,6])
b=a.reshape(3,1)
c=np.array([2,4,8,9,3])
d=c.reshape(1,5)
print(b)
print(d)
print(np.multiply(b,d))
print(b.dot(d))

[[1]
 [4]
 [6]]
[[2 4 8 9 3]]
[[ 2  4  8  9  3]
 [ 8 16 32 36 12]
 [12 24 48 54 18]]
[[ 2  4  8  9  3]
 [ 8 16 32 36 12]
 [12 24 48 54 18]]


In [ ]:
import numpy as np
a=np.array([1,3,5])
print(a.T)

In [10]:
import pandas as pd
d1 = {
    '城市':['neijing','nanjing','sjhanghai'],
    'huanbi' :[102,130,124],
    'dingji':[121,123,12],
    'tongbi':[120,234,23]
}
d = pd.DataFrame(d1,index=['c1','c2','c3'])
d.ix['c2']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


城市        nanjing
huanbi        130
dingji        123
tongbi        234
Name: c2, dtype: object

In [3]:
import numpy as np
x = np.random.uniform(-3.0,3.0,size=10)
print(x)
y = np.linspace(-3,3,10)
print(y)

[-1.998188    0.13188154  0.03154466 -1.77690421 -2.57039532  2.46053114
  1.20199953  0.60770629 -0.82295564 -0.30578242]
[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
