In [2]:
import numpy as np
import pandas as pd
import matplotlib as mat

In [6]:
array =  [[1,2,3],
         [2,3,4.21],
         [3,4,5]]
#convert normal array to nd array
array = np.array(array) 
print(array)

[[1.   2.   3.  ]
 [2.   3.   4.21]
 [3.   4.   5.  ]]


In [7]:
print('number of dimensions:', array.ndim) #dimension of array
print('shape:', array.shape) #shape of array 3 x 5
print('size:', array.size) #size of array
print('dtype', array.dtype)

number of dimensions: 2
shape: (3, 3)
size: 9
dtype float64


In [12]:
a = np.array([2,3,4], dtype=np.float16) #type of array 
print(a.dtype)

float16


In [8]:
a = np.zeros((3, 4)) #zero matrix
print(a)
a = np.ones((3, 4)) #one matrix
print(a)
a = np.eye(2) #unit matrix
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]


In [24]:
a = np.arange(0, 24, 2) #range array
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [26]:
a = a.reshape((3, 4)) #reshape array to 3 rows x 4 columns
print(a)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [28]:
a = np.linspace(1, 10, 20).reshape((4, 5)) #generate
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


In [9]:
a = np.arange(10, 41, 10)
b = np.arange(10, 26, 5)
print(a)
print(b)

[10 20 30 40]
[10 15 20 25]


In [10]:
#basic operations
c = a - b
c = a + b
c = a ** 2
c = np.sin(a)
print(c)
print(b == 15)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[False  True False False]


In [14]:
#multiply one by one xij * yij 
#warning * this is not matrix multiplication
a = a.reshape((2, 2))
b = b.reshape((2, 2)) 
print(a)
print(b)
c = a * b
print(c)
c.resize((4,1))
print(c)

[[10 20]
 [30 40]]
[[10 15]
 [20 25]]
[[ 100  300]
 [ 600 1000]]
[[ 100]
 [ 300]
 [ 600]
 [1000]]


In [41]:
#matrix multiplication
c_dot = np.dot(a, b)
c_dot = a.dot(b)
print(c_dot)

[[ 500  650]
 [1100 1450]]


In [44]:
a = np.random.random((2 ,4)) #shape of array random of [0, 1]
print(a)

[[0.70125113 0.08940205 0.0017395  0.04513172]
 [0.29047462 0.15144242 0.95743226 0.93760053]]


In [58]:
# axis=0 means sum by columns
# axis=1 means sum by rows
print(np.sum(a, axis=1)) 
print(np.min(a, axis=0))
print(np.max(a, axis=1))

[0.8375244  2.33694983]
[0.29047462 0.08940205 0.0017395  0.04513172]
[0.70125113 0.95743226]


In [78]:
a = np.arange(0, 12).reshape((3, 4))
print(a)

index_min = np.argmax(a)# get index of array 
print(index_min)
print(a.mean())
print(np.median(a))
print(np.cumsum(a))
print(np.diff(a))
print(np.nonzero(a)) #get index of nonzero in array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
5.5
5.5
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [84]:
a = np.arange(14, 2, -1).reshape((3, 4))
print(a)
print(np.sort(a)) #sort by column
print(a.T) # matrix tanspose
# if < min, then = min, if > max, then = max
print(np.clip(a, 3, 5)) 

print(np.mean(a, axis=0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 4 3]]
[10.  9.  8.  7.]


In [88]:
a = np.arange(3, 15).reshape((3, 4))
print(a, '\n')
print(a[2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]] 

[11 12 13 14]


In [23]:
print(np.random.randint(3, 8, (10, 10)))

[[6 4 3 3 6 5 3 6 7 3]
 [3 5 3 6 7 7 6 7 3 3]
 [4 6 5 5 6 7 7 5 7 5]
 [7 7 4 6 3 3 4 4 4 4]
 [6 7 3 7 4 6 5 4 4 5]
 [3 5 3 4 7 6 5 6 6 4]
 [4 5 4 4 6 6 7 5 3 3]
 [5 3 7 7 5 3 5 4 5 5]
 [4 5 3 7 6 7 7 5 5 6]
 [6 4 4 4 5 7 7 5 5 7]]


In [24]:
x = np.random.randint(3, 8, (2, 3))
print(np.std(x))
np.var(x)
np.mean(x)

1.118033988749895


In [3]:
array_a = np.array([1, 2, 3, 4, 7, 9]).reshape(2, 3)
array_b = np.array([2, 4, 2, 6, 8, 2]).T.reshape(3, 2)
array_c = array_a.dot(array_b)
# array_c = array_a.multiply(array_b)
print(array_c)
# print(array_a)

[[30 22]
 [94 76]]


In [ ]:
x = np.array()